### 1. Purpose and Advantages of NumPy:
- **Purpose**: NumPy is used for efficient numerical computations.
- **Advantages**:
  - Efficient memory storage with `ndarray`.
  - Vectorized operations (no need for loops).
  - Support for linear algebra, FFT, random sampling.
  - Interoperability with C/C++ and Fortran.

> **Enhancement**: Native Python lists are slow for numerical tasks. NumPy enables fast, optimized performance using C-backed arrays and operations.


### 2. `np.mean()` vs `np.average()`:
| Feature         | `np.mean()`            | `np.average()`               |
|----------------|------------------------|------------------------------|
| Purpose         | Computes simple mean   | Computes weighted average    |
| Weights param   | Not supported          | Supports `weights` argument  |
| Use case        | When equal importance  | When elements have weights   |
```python
import numpy as np
a = np.array([1, 2, 3, 4])
print(np.mean(a))               # Output: 2.5
print(np.average(a))            # Output: 2.5
print(np.average(a, weights=[1, 2, 3, 4]))  # Output: 3.0
```

### 3. Reversing Arrays:
```python
a1 = np.array([1, 2, 3])
print(a1[::-1])  # 1D reversal

a2 = np.array([[1, 2], [3, 4]])
print(np.flip(a2, axis=0))  # Flip rows
print(np.flip(a2, axis=1))  # Flip columns
```

### 4. Determining Data Type:
```python
arr = np.array([1.5, 2.3])
print(arr.dtype)  # float64
```
> **Importance**: Choosing proper data types (e.g., `int32` vs `float64`) saves memory and speeds up computation.


### 5. `ndarray` and Key Features:
- **ndarray**: Core data structure in NumPy.
- **Features**:
  - Fixed size
  - Homogeneous data type
  - Supports broadcasting, slicing
- **Difference** from lists:
  - Faster computation
  - Vectorized operations
  - Less memory usage


### 6. NumPy vs Python Lists:
```python
# NumPy is faster for large arrays
arr = np.arange(1e6)
lst = list(range(int(1e6)))

# NumPy uses optimized C code, less memory
```


### 7. `vstack()` vs `hstack()`:
```python
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))  # Vertical stacking
print(np.hstack((a, b)))  # Horizontal stacking
```

### 8. `fliplr()` vs `flipud()`:
```python
a = np.array([[1, 2], [3, 4]])
print(np.fliplr(a))  # Left-Right
print(np.flipud(a))  # Up-Down
```

### 9. `array_split()`:
```python
arr = np.arange(10)
print(np.array_split(arr, 3))  # Splits into 3 uneven parts if needed
```

### 10. Vectorization and Broadcasting:
- **Vectorization**: No explicit loop; operates on entire array.
- **Broadcasting**: Handles arrays of different shapes.
```python
a = np.array([1, 2, 3])
print(a + 5)  # Broadcasting scalar
```
> These features make NumPy fast and memory-efficient.


In [2]:
import numpy as np
import math

# 1. 3x3 array with random integers
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", arr)
print("Transposed Array (rows and columns interchanged):\n", arr.T)

# 2. Reshape 1D array
arr1d = np.arange(10)
print("2x5:\n", arr1d.reshape(2, 5))
print("5x2:\n", arr1d.reshape(5, 2))

# 3. 4x4 array and zero border
arr_float = np.random.rand(4, 4)
bordered = np.pad(arr_float, pad_width=1, mode='constant', constant_values=0)
print("With border:\n", bordered)

# 4. Array with step
step_arr = np.arange(10, 61, 5)
print("Step array:\n", step_arr)

# 5. Case transformations
words = np.array(['python', 'numpy', 'pandas'])
print("Upper:", np.char.upper(words))
print("Lower:", np.char.lower(words))
print("Title:", np.char.title(words))

# 6. Space between characters
spaced = np.char.join(' ', words)
print("Spaced:", spaced)

# 7. Element-wise ops
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Add:\n", a + b)
print("Subtract:\n", a - b)
print("Multiply:\n", a * b)
print("Divide:\n", a / b)

# 8. Identity and diagonal
identity = np.eye(5)
print("Identity:\n", identity)
print("Diagonal:", np.diag(identity))

# 9. Random integers and primes
rand_arr = np.random.randint(0, 1001, 100)
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
primes = rand_arr[np.vectorize(is_prime)(rand_arr)]
print("Primes:", primes)

# 10. Daily temperatures and weekly average
temps = np.random.randint(20, 40, size=30)
weekly_avg = temps.reshape(6, 5).mean(axis=1)
print("Weekly Averages:", weekly_avg)

Original Array:
 [[60 71 61]
 [ 4 86 42]
 [48 30 44]]
Transposed Array (rows and columns interchanged):
 [[60  4 48]
 [71 86 30]
 [61 42 44]]
2x5:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
With border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.44447964 0.43933677 0.06471037 0.26856502 0.        ]
 [0.         0.23267621 0.11079967 0.07376245 0.78516342 0.        ]
 [0.         0.76420363 0.13076454 0.8998761  0.94137916 0.        ]
 [0.         0.99882732 0.7355757  0.90099682 0.18658012 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
Step array:
 [10 15 20 25 30 35 40 45 50 55 60]
Upper: ['PYTHON' 'NUMPY' 'PANDAS']
Lower: ['python' 'numpy' 'pandas']
Title: ['Python' 'Numpy' 'Pandas']
Spaced: ['p y t h o n' 'n u m p y' 'p a n d a s']
Add:
 [[ 6  8]
 [10 12]]
Subtract:
 [[-4 -4]
 [-4 -4]]
Multiply:
 [[ 5 12]
 [21 32]]
Divide:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Identi